require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/public_recipes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PublicRecipe. As you add validations to PublicRecipe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PublicRecipe.create! valid_attributes
      get public_recipes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      public_recipe = PublicRecipe.create! valid_attributes
      get public_recipe_url(public_recipe)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_public_recipe_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      public_recipe = PublicRecipe.create! valid_attributes
      get edit_public_recipe_url(public_recipe)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PublicRecipe" do
        expect {
          post public_recipes_url, params: { public_recipe: valid_attributes }
        }.to change(PublicRecipe, :count).by(1)
      end

      it "redirects to the created public_recipe" do
        post public_recipes_url, params: { public_recipe: valid_attributes }
        expect(response).to redirect_to(public_recipe_url(PublicRecipe.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PublicRecipe" do
        expect {
          post public_recipes_url, params: { public_recipe: invalid_attributes }
        }.to change(PublicRecipe, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post public_recipes_url, params: { public_recipe: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested public_recipe" do
        public_recipe = PublicRecipe.create! valid_attributes
        patch public_recipe_url(public_recipe), params: { public_recipe: new_attributes }
        public_recipe.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the public_recipe" do
        public_recipe = PublicRecipe.create! valid_attributes
        patch public_recipe_url(public_recipe), params: { public_recipe: new_attributes }
        public_recipe.reload
        expect(response).to redirect_to(public_recipe_url(public_recipe))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        public_recipe = PublicRecipe.create! valid_attributes
        patch public_recipe_url(public_recipe), params: { public_recipe: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested public_recipe" do
      public_recipe = PublicRecipe.create! valid_attributes
      expect {
        delete public_recipe_url(public_recipe)
      }.to change(PublicRecipe, :count).by(-1)
    end

    it "redirects to the public_recipes list" do
      public_recipe = PublicRecipe.create! valid_attributes
      delete public_recipe_url(public_recipe)
      expect(response).to redirect_to(public_recipes_url)
    end
  end
end
